//go:build ignore

// Command gen regenerates tables.go from the Unicode Character
// Database. Run via "go generate ./internal/wcwidth" (see the
// generate directive in wcwidth.go) or directly with "go run gen.go".
// It requires network access to unicode.org; the module itself has no
// such dependency at build or run time — this is dev-only tooling (see
// docs/DESIGN.md §2 and §9's wide-rune-table risk note).
//
// It derives two disjoint, sorted, merged range tables:
//
//   - zeroWidth: combining marks (General_Category Mn/Me, from
//     DerivedGeneralCategory.txt) plus a handful of zero-width format
//     characters (ZWSP/ZWNJ/ZWJ/direction marks, BOM) that are Cf and
//     so aren't covered by the Mn/Me rule.
//   - wide: East Asian Wide/Fullwidth characters (EastAsianWidth.txt)
//     plus code points with a default Emoji_Presentation
//     (emoji-data.txt) — EastAsianWidth.txt alone under-covers actual
//     terminal rendering width for most emoji.
//
// Where a code point would fall in both, zeroWidth wins (a combining
// mark rendering as double-width would be visually wrong); wide's
// ranges are subtracted accordingly.
package main

import (
	"bufio"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

const ucdBase = "https://www.unicode.org/Public/UCD/latest/ucd/"

type rng struct{ lo, hi rune }

var lineRE = regexp.MustCompile(`^([0-9A-Fa-f]{4,6})(?:\.\.([0-9A-Fa-f]{4,6}))?\s*;\s*(\S+)`)

func fetch(path string) []byte {
	resp, err := http.Get(ucdBase + path)
	if err != nil {
		log.Fatalf("fetch %s: %v", path, err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		log.Fatalf("fetch %s: status %s", path, resp.Status)
	}
	b, err := io.ReadAll(resp.Body)
	if err != nil {
		log.Fatalf("read %s: %v", path, err)
	}
	return b
}

// parse scans a UCD-format file ("HHHH..HHHH ; Field # comment" or
// "HHHH ; Field # comment") and returns the code point ranges of every
// line whose Field is in want.
func parse(data []byte, want map[string]bool) []rng {
	var out []rng
	sc := bufio.NewScanner(strings.NewReader(string(data)))
	for sc.Scan() {
		line := sc.Text()
		if i := strings.IndexByte(line, '#'); i >= 0 {
			line = line[:i]
		}
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		m := lineRE.FindStringSubmatch(line)
		if m == nil {
			continue
		}
		if !want[m[3]] {
			continue
		}
		lo, err := strconv.ParseInt(m[1], 16, 32)
		if err != nil {
			log.Fatal(err)
		}
		hi := lo
		if m[2] != "" {
			hi, err = strconv.ParseInt(m[2], 16, 32)
			if err != nil {
				log.Fatal(err)
			}
		}
		out = append(out, rng{lo: rune(lo), hi: rune(hi)})
	}
	if err := sc.Err(); err != nil {
		log.Fatal(err)
	}
	return out
}

// merge sorts and coalesces overlapping/adjacent ranges.
func merge(rs []rng) []rng {
	if len(rs) == 0 {
		return nil
	}
	sort.Slice(rs, func(i, j int) bool { return rs[i].lo < rs[j].lo })
	out := []rng{rs[0]}
	for _, r := range rs[1:] {
		last := &out[len(out)-1]
		if r.lo <= last.hi+1 {
			if r.hi > last.hi {
				last.hi = r.hi
			}
			continue
		}
		out = append(out, r)
	}
	return out
}

// subtract removes any part of b's ranges from a's ranges.
func subtract(a, b []rng) []rng {
	var out []rng
	for _, ar := range a {
		lo := ar.lo
		for _, br := range b {
			if br.hi < lo || br.lo > ar.hi {
				continue
			}
			if br.lo > lo {
				out = append(out, rng{lo, br.lo - 1})
			}
			if br.hi+1 > lo {
				lo = br.hi + 1
			}
		}
		if lo <= ar.hi {
			out = append(out, rng{lo, ar.hi})
		}
	}
	return out
}

func main() {
	eaw := fetch("EastAsianWidth.txt")
	dgc := fetch("extracted/DerivedGeneralCategory.txt")
	emoji := fetch("emoji/emoji-data.txt")

	wide := parse(eaw, map[string]bool{"W": true, "F": true})
	wide = append(wide, parse(emoji, map[string]bool{"Emoji_Presentation": true})...)
	wide = merge(wide)

	zero := parse(dgc, map[string]bool{"Mn": true, "Me": true})
	zero = append(zero,
		rng{0x200B, 0x200F}, // ZWSP, ZWNJ, ZWJ, LRM, RLM (Cf, not Mn/Me)
		rng{0xFEFF, 0xFEFF}, // ZWNBSP / BOM (Cf)
	)
	zero = merge(zero)

	wide = subtract(wide, zero)

	writeTables(zero, wide)
	fmt.Fprintf(os.Stderr, "wrote tables.go: %d zero-width ranges, %d wide ranges\n", len(zero), len(wide))
}

func writeTables(zero, wide []rng) {
	f, err := os.Create("tables.go")
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	w := bufio.NewWriter(f)
	fmt.Fprintln(w, "// Code generated by gen.go from the Unicode Character Database; DO NOT EDIT.")
	fmt.Fprintln(w, "// Regenerate with: go generate ./internal/wcwidth")
	fmt.Fprintln(w, "//")
	fmt.Fprintln(w, "// Source: https://www.unicode.org/Public/UCD/latest/ucd/, Unicode 17.0.0.")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "package wcwidth")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "// zeroWidth holds combining marks (General_Category Mn/Me) plus a")
	fmt.Fprintln(w, "// handful of zero-width format characters (ZWSP/ZWNJ/ZWJ/direction")
	fmt.Fprintln(w, "// marks, BOM) not covered by the Mn/Me rule. Sorted, non-overlapping.")
	fmt.Fprintln(w, "var zeroWidth = []Range{")
	for _, r := range zero {
		fmt.Fprintf(w, "\t{0x%04X, 0x%04X},\n", r.lo, r.hi)
	}
	fmt.Fprintln(w, "}")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "// wide holds East Asian Wide/Fullwidth characters plus code points")
	fmt.Fprintln(w, "// with a default Emoji_Presentation. Sorted, non-overlapping, and")
	fmt.Fprintln(w, "// disjoint from zeroWidth.")
	fmt.Fprintln(w, "var wide = []Range{")
	for _, r := range wide {
		fmt.Fprintf(w, "\t{0x%04X, 0x%04X},\n", r.lo, r.hi)
	}
	fmt.Fprintln(w, "}")
	if err := w.Flush(); err != nil {
		log.Fatal(err)
	}
}
